package mainCharacter.Items;

public enum Item {
    apple(1 , "apple", "яблоко") ,
    banana(2 , "banana", "банан") ,
    orange(3 , "orange", "апельсин") ,
    soup(4 , "soup", "суп") ,
    grape(5 , "grape", "виноград") ,
    seeds(6 , "seeds", "семена") ,
    snack(7 , "snack", "закуска") ,
    chips(8 , "chips", "чипсы") ,
    bottleOfWater(9 , "bottle of water", "бутылка воды") ,
    packCookies(10 , "cookies pack", "пакет печенья") ,
    dryRation(11 , "dry ration", "сухой паек") ,
    herbalEnergyDrink(12 , "herbal energy drink", "травяной энергетик") ,
    cannedCatFood(13 , "canned cat food", "корм для кошек") ,
    cannedTuna(14 , "canned tuna", "консервированный тунец") ,
    energyBar(15 , "energy bar", "энергетический батончик") ,
    bacon(16 , "bacon", "бекон") ,
    muesliBar(17 , "muesli bar", "батончик мюсли") ,
    pickles(18 , "pickles", "соленья") ,
    stew(19 , "stew", "тушенка") ,
    powerEngineer(20 , "power engineer", "энергетик") ,
    chocolateBar(21 , "chocolate bar", "плитка шоколада") ,
    bagOfBuckwheat(22 , "a bag of buckwheat", "мешок гречки") ,
    riceCerealBag(23 , "rice cereal bag", "мешок риса") ,
    meat(24 , "meat", "мясо") ,
    cookedMeat(25 , "cooked Meat", "приготовленное мясо") ,
    sandwich(26 , "sandwich", "бутерброд") ,
    bread(27 , "bread", "хлеб") ,
    flakesCrackers(28 , "flakes \"crackers\"", "хлопушки") ,
    crackers(29 , "crackers", "крекеры") ,
    bun(30 , "bun", "булочка") ,
    fish(31 , "fish", "рыба") ,
    cookedFish(32 , "cooked fish", "приготовленная рыба") ,
    vodka(33 , "vodka", "водка") ,
    whiskey(34 , "whiskey", "виски") ,
    scotch(35 , "scotch", "Коньяк") ,
    liquor(36 , "liquor", "ликер") ,
    beer(37 , "beer", "пиво") ,
    medicines(38 , "medicines", "лекарства") ,
    aloe(39 , "aloe", "алоэ") ,
    antiseptic(40 , "antiseptic", "антисептик") ,
    painkiller(41 , "painkiller", "обезболивающее") ,
    bandage(42 , "bandage", "повязка") ,
    baseballBat(43 , "baseball bat", "бейсбольная бита") ,
    knife(44 , "knife", "нож") ,
    gun(45 , "gun", "пистолет") ,
    cartridges(46 , "cartridges", "патроны") ,
    slingshot(47 , "slingshot", "рогатка") ,
    signalPistol(48 , "signal pistol", "сигнальный пистолет") ,
    flare(49 , "flare", "сигнальная ракета") ,
    spear(50 , "a spear", "копье") ,
    axe(51 , "axe", "топор") ,
    fishingRod(52 , "fishing rod", "удочка") ,
    setOfTools(53 , "set of tools", "набор инструментов") ,
    ultravioletLamp(54 , "ultraviolet lamp", "УФ лампа") ,
    flashlight(55 , "flashlight", "фонарик") ,
    batteries(56 , "batteries", "батарейки") ,
    walkieTalkie(57 , "walkie-talkie", "рация") ,
    compass(58 , "compass", "компас") ,
    lighter(59 , "lighter", "зажигалка") ,
    flint(60 , "flint", "кремень") ,
    matches(61 , "matches", "спички") ,
    magnifyingGlass(62 , "magnifying glass", "увеличительное стекло") ,
    stick(63 , "stick", "палка") ,
    magazine(64 , "magazine", "журнал") ,
    newspaper(65 , "newspaper", "газета") ,
    leaves(66 , "leaves", "листья") ,
    branch(67 , "branch", "ветвь") ,
    log(68 , "log", "бревно") ,
    bills(69 , "bills", "счета") ,
    book(70 , "book", "книга") ,
    bookSS(71 , "book \"Sorrow of satan\"", "книга \"Скорбь сатаны\" ") ,
    rope(72 , "rope", "веревка") ,
    insulatingTape(73 , "insulating tape", "изолента") ,
    documentation(74 , "documentation", "документация") ,
    leaflet(75 , "leaflet", "листовка") ,
    bottleOfBleach(76 , "a bottle of bleach", "бутылка отбеливателя") ,
    gasMaskFilter(77 , "gas mask filter", "фильтр противогаза") ,
    packSig(78 , "a pack of cigarettes", "пачка сигарет") ,
    sharpening(79 , "sharpening", "заточка") ,
    bottleOfGasoline(80 , "bottle of gasoline", "бутылка бензина") ,
    canOfGasoline(81 , "can of gasoline", "канистра с бензином") ,
    watch(82 , "watch", "часы") ,
    bottle(83 , "bottle", "бутылка") ,
    flask(84 , "flask", "колба") ,
    pouch(85 , "pouch", "мешочек") ,
    pot(86 , "pot", "кастрюля") ,
    laptop(87 , "laptop", "ноутбук") ,
    soap(88 , "soap", "мыло") ,
    paintBrush(89 , "paint brush", "кисть") ,
    toy(90 , "toy", "игрушка") ,
    guitar(91 , "guitar", "гитара") ,
    coins(92 , "coins", "монеты") ,
    resin(93 , "resin", "смола") ,
    textile(94 , "textile", "текстиль") ,
    marijuanaBag(95 , "marijuana bag", "мешок марихуаны"),
    stone(96 , "stone", "камень"),
    groundStone(97 , "ground stone", "молотый камень") ,
    torch(98 , "torch", "факел"),
    worm(99 , "worm", "червь"),
    cleaningBottle(98 , "cleaning bottle", "чистящая бутылка") ,
    drinkingWaterBottle(99 , "drinking water bottle", "бутылка с питьевой водой") ,
    pureWater(100 , "pure water", "чистая вода") ,
    cleanWaterBottle(101 , "clean water bottle", "бутылка с чистой водой") ,
    finishedFishingRot(102 , "finished fishing rot", "готовая удочка") ,
    cookedRise(103 , "cooked rise", "приготовленный рис") ,
    cookedBuckwheat(104 , "cooked buckwheat", "вареная гречка"),
    campfire(105 , "campfire", "костер"),
    water (106 , "water", "вода"),
    gasoline(107 , "gasoline", "бензин");

    Item(int id, String name, String nameRU) {
        this.id = id;
        this.name = name;
        this.nameRU = nameRU;
    }

    final int id;
    final String name;
    final String nameRU;

}
